# Generated by Django 5.1.2 on 2024-10-31 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('nfe', models.IntegerField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField()),
                ('cliente', models.CharField(max_length=255)),
                ('volumes', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('un', models.CharField(max_length=6)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nfe_remessa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.shipping')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingStorage',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('un', models.CharField(max_length=6)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nfe_remessa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.shipping')),
            ],
        ),
    ]
