# Generated by Django 5.1.2 on 2024-11-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0002_alter_shippingitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingitem',
            name='id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingstorage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
