# Generated by Django 5.1.2 on 2024-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0003_alter_shippingitem_id_alter_shippingstorage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
